import Foundation

/// Centralized Malaysian-voice copy so tone stays consistent across screens.
enum Copy {
    static let homeGreeting = "Hungry?"
    static let homeSubtext = "Okay, what we doing today?"
    static let gengComingSoon = "Soon lah 👀 Geng mode is still cooking."

    static let soloMoodPrompt = "What mood today?"
    static let soloMoodSubtext = "Craving something in particular?"
    static let soloAnythingLah = "🎲 Anything lah"
    static let anythingLahSubtext = "Surprise me!"
    static let budgetAnythingSubtext = "No limits"
    static let soloBudgetPrompt = "How much you wanna spend?"
    static let soloBudgetSubtext = "per person ya!"
    static let soloDistancePrompt = "How far willing to jalan?"
    static let soloDistanceSubtext = "No sweat, we'll find something nice."
    static let soloCTA = "MAKANAPA?"

    static let moodLightSubtext = "Something lighter"
    static let moodQuickSubtext = "Fast & convenient"

    static let moodNasiKandarSubtext = "Kandar power"
    static let moodAyamGepukSubtext = "Smashed, spicy, sedap"
    static let moodNasiPadangSubtext = "Rendang, gulai, the works"
    static let moodMeeGorengSubtext = "Wok hei, always hits"
    static let moodNasiLemakSubtext = "Anytime, anywhere"
    static let moodCharKueyTeowSubtext = "Smoky and shiok"
    static let moodBananaLeafRiceSubtext = "Banjir gravy, no regrets"
    static let moodDimSumSubtext = "Small plates, big satisfaction"
    static let moodCustomCravingPlaceholder = "Cakap je nak makan apa..."

    static let thinking = "Thinking so you don't have to..."
    static let thinkingStep1 = "Finding nearby spots..."
    static let thinkingStep2 = "Checking what fits you..."
    static let thinkingStep3 = "Picking the best one..."

    static let rerollHeadline = "Cari lagi!"
    static let rerollLine1 = "Same preferences"
    static let rerollLine2 = "Different spot"
    static let rerollLine3 = "Still sedap, don't worry"

    static let noResultHeadline = "No spots found nearby"
    static let noResultDetail = "Try increasing the distance or changing your preferences."

    static let trustBadgeWhileUsing = "While using"
    static let trustBadgePrivacy = "We respect privacy"
    static let trustBadgeNearby = "Nearby spots"

    static let resultIntro = "MakanApa says..."
    static let resultThatsIt = "Settled."
    static let jomMakan = "JOM MAKAN"
    static let pickAgain = "Cari lain lah"
    static let anythingLabel = "Anything"

    static let emptyState = "Wah, demanding ah 😭 Try increasing your distance."

    static let connectionErrorHeadline = "Aiyo 😭"
    static let connectionErrorDetail = "Connection gone.\nCouldn't find makan right now."
    static let genericAPIErrorHeadline = "Aiyo 😭"
    static let genericAPIErrorDetail = "MakanApa blur kejap.\nTry again in a bit."
    static let tryAgain = "Try again"
    static let backHome = "Back home"

    static let locationDenied = "Can't find makan if we don't know where you are 👀"
    static let locationPrivacyLine = "We only use your location while you're using MakanApa."

    static let tagline = "Less thinking. More makan."
    static let aboutDescription = "MakanApa helps you decide what to eat. Tell it your mood and budget, and it picks food nearby — less thinking, more makan."
    static let privacyPolicyURL = "https://makanapa.hakeemiridza.com/privacy"

    static let loginTagline = "Makan dulu. Decide later."
    static let signIn = "Sign in"
    static let loginInvalidCredentials = "Email or password doesn't match."

    static let communityHeadlineUniversityFormat = "%@ tengah makan apa? 👀"
    static let communitySubtitleUniversityFormat = "Popular around %@"
    static let communityHeadlineAreaFormat = "%@ tengah makan apa? 👀"
    static let communitySubtitleAreaFormat = "Popular around %@"
    static let communityHeadlinePublic = "What's trending near you"
    static let communitySubtitlePublic = "Trending picks nearby"
    static let communityEmptyHeadline = "Nothing trending yet 👀"
    static let communityEmptyDetail = "Every recommendation your community picks helps build this page."
    static let communityLocationPromptHeadline = "See what's trending around you"
    static let communityLocationPromptDetail = "MakanApa uses your location to find popular picks nearby."
    static let communityLocationEnable = "Enable Location"
    static let communityLocationDeniedHeadline = "Location is off"
    static let communityLocationDeniedDetail = "Turn on location access to see what's trending nearby."
    static let communityLocationOpenSettings = "Open Settings"

    // Kept short deliberately — this title sits inline between "Cancel" and this save button,
    // and a longer pair (e.g. "Choose your community" / "Save community") truncates on
    // standard-width devices. The subtitle below already spells out what this screen is for.
    static let communityChooseCommunityTitle = "Community"
    static let communityChooseCommunitySubtitle = "This helps MakanApa show what's popular around people in your community."
    static let communityChooseCommunityFooter = "University verification will be available later."
    static let communityChooseCommunitySave = "Save"
    static let communityChangeCommunityCTA = "Change ›"
    static let communityAssignCommunityCTA = "Choose ›"
    static let communityUniversitiesSectionHeader = "UNIVERSITIES"
    static let communityAreasSectionHeader = "AREA"
    static let communityRequestUniversityRow = "Can't find your university? Request it"
    static let communityRequestAreaRow = "Can't find your area? Request it"
    // Same inline-title-truncation reasoning as communityChooseCommunityTitle above — flanked
    // by "Cancel" and "Send request", so it needs to stay short.
    static let communityRequestSheetTitle = "Request"
    static let communityRequestUniversityPlaceholder = "e.g. Universiti Malaya"
    static let communityRequestAreaPlaceholder = "e.g. Shah Alam, Cheras, your neighbourhood"
    static let communityRequestSubmit = "Send request"
    static let communityRequestSentConfirmation = "Thanks, we'll take a look! 👀"

    // Community posts ("What KU is saying")
    static let communityPostsSectionFormat = "WHAT %@ IS SAYING"
    static let communityPostsSectionPublic = "WHAT PEOPLE ARE SAYING"
    static let communityPostsSeeAll = "See all ›"
    static let communityPostsEmptyHeadline = "No one's said anything yet"
    static let communityPostsEmptyDetailFormat = "Be the first to share what %@ is eating 🍛"
    static let communityPostsJoinPrompt = "Join a university or area community to see and share thoughts."
    static let communityPostsComposePlaceholder = "Share a thought… best teh tarik? new spot? 👀"
    static let communityPostsReplyPlaceholder = "Write a reply…"
    static let communityPostsShareCTA = "Share a thought"
    static let communityPostsPost = "Post"
    static let communityPostsReply = "Reply"
    static let communityPostsTagPlace = "Tag a place"
    static let communityPostsTagPlaceSearch = "Search places on MakanApa"
    static let communityPostsViewAllRepliesFormat = "View all %d replies"
    static let communityPostsReportTitle = "Report post"
    static let communityPostsReportDetail = "Reports are anonymous. We review every one, and posts with several reports are hidden automatically."
    static let communityPostsReportNotePlaceholder = "Anything else we should know? (optional)"
    static let communityPostsReportSubmit = "Send report"
    static let communityPostsReportedToast = "Thanks — we'll take a look. You won't see this post again."
    static let communityPostsBlockTitleFormat = "Block %@?"
    static let communityPostsBlockDetail = "You won't see each other's posts or replies. You can unblock in Settings → Blocked users."
    static let communityPostsDeleteTitle = "Delete this post?"
    static let communityPostsGenericError = "Couldn't post that right now. Try again in a bit."
    static let communityPostsGuidelines = "Keep it friendly and about food. No links, ads or personal attacks."
    static let supportEmail = "support@hakeemiridza.com"

    static let communityAddPlaceMenuItem = "Add a place"
    static let communityAddPlaceCTA = "Know a good spot? Add it →"
    static let communityMyPlacesMenuItem = "My places"
    static let communitySearchTitle = "Add a place"
    static let communitySearchSubtitle = "Found somewhere sedap? 👀 Let's check if we know it first."
    static let communitySearchPlaceholder = "Search for a place"
    static let communitySearchExistingLabel = "Already on MakanApa"
    static let communitySearchGoogleLabel = "Found on Google"
    static let communityCantFindHeadline = "Not on Google? No problem."
    static let communityCantFindDetail = "Small places deserve to be discovered too."
    static let communityAddManually = "Add it manually →"
    static let communityDetailsTitle = "Details"
    static let communityLocationStepTitle = "Location"
    static let communityUseCurrentLocation = "📍 Use my current location"
    static let communityChooseOnMap = "🗺 Choose on map"
    static let communityLocationReadyDetail = "We'll use where you are right now. This place should be somewhere nearby."
    static let communityLocationImmutable = "Set when this place was added. Location can't be changed."
    static let communityConfirmLocation = "Confirm this location"
    static let communityRecenterOnMe = "Recenter on me"
    static let communityReviewTitle = "Review"
    static let communitySubmitForReview = "Submit for review"
    static let communitySubmissionSuccessHeadline = "Sent for review!"
    static let communitySubmissionSuccessDetail = "We'll check the place before it shows up around MakanApa."
    static let communityMyPlacesTitle = "My places"
    static let communityStatusPending = "Pending review"
    static let communityStatusApproved = "Approved · Now discoverable on MakanApa"
    static let communityStatusChangesRequested = "Changes requested"
    static let communityStatusRejected = "Not approved"
    static let communityStatusCancelled = "Cancelled"
    static let communityUpdateSubmission = "Update submission"
    static let communityCancelSubmission = "Cancel submission"

    static let communityStepFormat = "Step %d of 3 · %@"
    static let communityDetailsHeadline = "Tell us about this place"
    static let communitySpendFooter = "Usually around how much per person?"
    static let communitySpendErrorInline = "Enter an estimated spend per person."
    static let communityAddMoreDetailsTitle = "Add more details"
    static let communityAddMoreDetailsSubtitle = "Address, phone & socials"
    static let communityAddMenuTitle = "Add menu"
    static let communityAddMenuSubtitle = "Help people know what's good here."
    static let communityBlankIsFine = "You can leave these blank — the community can help complete them later."
    static let communityAddMenuItemCTA = "Add another item"
}
